### ISSUE TITLE
Publish to nixpkgs

### ISSUE THREAD

**Issue by wvffle** [pkulak/matui#12]
Hey! Awesome work here!

Have you considered publishing a package to nixpkgs?

**Comment by pkulak** [comment]
Oh man, I really want to. If only so I can stop compiling the damn thing myself every time some random dep changes. It would be my first ever package though, so I'd have to go through a whole learning process, plus actually get it accepted. It's on my shortlist though!

**Comment by pkulak** [comment]
Not gonna do it, myself, sorry. I tried to submit a much simpler project of mine and the PR was unceremoniously closed. Anyone else can do it, of course, but trying to jam this thing through a nerd bureaucracy is just not how I'm gonna spend my free time. :D

**Comment by wvffle** [comment]
Sure, I migrated my entire nixos installation to flakes just for your matui :D
