### ISSUE TITLE
crashing when opening one of the channel Helix channel.

### ISSUE THREAD

**Issue by siddharthagudgunti** [pkulak/matui#5]
Below is the screen log: when crash happened. The screen jumbled up.
OS: ArtixLinux on WSL2.
matui version: 0.4.4.1 from AUR.
terminal: wezterm

```
thread 'main' panicked at 'byte in
dex 317 is out of bounds of `> <@sharpenedblade:matrix.org> Power?──────────────────────────────────────╯

                           I attempted to replicate the error with> PowerPC (with the backronym Performance Optimization With Enha
nced RISC – Performance Computing, sometimes abbreviated as PPC) is a reduced instruction set computer (RISC) instruction set arch
itecture (ISA) create`[...]', src/widgets/message.rs:405:10
                           ╷                               note: run with `RUST_BACKTRACE=1` environment variable to display a bac
ktrace                     │ Diogenesoftoronto 3 hours ago
      %
```
Other channels work OK. 
Let me know if you need more info.

**Comment by pkulak** [comment]
Okay, yeah, this is a bug. Looks like I'm using byte indexing on a string, which is never good. I'll see what I can do about it. Thanks for reporting!

**Comment by pkulak** [comment]
Nope, that wasn't even it. Should be fixed with this commit though:

https://github.com/pkulak/matui/commit/1fd6168a95268b07a750d7ee3f5b51702f67e9b8
